export const V1_CATEGORIES_URL = 'https://api.thecatapi.com/v1/categories';

export const CATEGORY_FETCH_START = 'SIDEBAR_LAYOUT/CATEGORY_FETCH_START';
export const CATEGORY_FETCH_SUCCESS = 'SIDEBAR_LAYOUT/CATEGORY_FETCH_SUCCESS';
export const CATEGORY_FETCH_FAIL = 'SIDEBAR_LAYOUT/CATEGORY_FETCH_FAIL';
export const SET_SELECTED_CATEGORY = 'SIDEBAR_LAYOUT/SET_SELECTED_CATEGORY';
